import { NvmeCommand } from "./types";

export const adminCommands: NvmeCommand[] = [
  {
    id: "admin-delete-sq",
    name: "Delete I/O Submission Queue",
    opcode: 0x00,
    type: "admin",
    description:
      "Deletes an I/O Submission Queue. All commands submitted but not yet completed are aborted.",
    fields: [
      {
        name: "QID",
        dword: 10,
        bitStart: 0,
        bitEnd: 15,
        description: "Queue Identifier — identifies the queue to delete",
      },
    ],
    relatedCommands: ["admin-create-sq"],
  },
  {
    id: "admin-create-sq",
    name: "Create I/O Submission Queue",
    opcode: 0x01,
    type: "admin",
    description:
      "Creates an I/O Submission Queue with the specified attributes including queue size and priority.",
    fields: [
      {
        name: "QID",
        dword: 10,
        bitStart: 0,
        bitEnd: 15,
        description: "Queue Identifier",
      },
      {
        name: "QSIZE",
        dword: 10,
        bitStart: 16,
        bitEnd: 31,
        description: "Queue Size — 0-based value (0 = 1 entry)",
      },
      {
        name: "PC",
        dword: 11,
        bitStart: 0,
        bitEnd: 0,
        description: "Physically Contiguous",
        values: { 0: "Not contiguous", 1: "Physically contiguous" },
      },
      {
        name: "QPRIO",
        dword: 11,
        bitStart: 1,
        bitEnd: 2,
        description: "Queue Priority",
        values: {
          0: "Urgent",
          1: "High",
          2: "Medium",
          3: "Low",
        },
      },
      {
        name: "CQID",
        dword: 11,
        bitStart: 16,
        bitEnd: 31,
        description: "Completion Queue Identifier",
      },
      {
        name: "NVMSETID",
        dword: 12,
        bitStart: 0,
        bitEnd: 15,
        description: "NVM Set Identifier",
      },
    ],
    relatedCommands: ["admin-delete-sq", "admin-create-cq"],
  },
  {
    id: "admin-get-log-page",
    name: "Get Log Page",
    opcode: 0x02,
    type: "admin",
    description:
      "Returns a log page to the host. Log pages provide information about the controller, namespace, or NVM subsystem.",
    fields: [
      {
        name: "LID",
        dword: 10,
        bitStart: 0,
        bitEnd: 7,
        description: "Log Page Identifier",
      },
      {
        name: "LSP",
        dword: 10,
        bitStart: 8,
        bitEnd: 11,
        description: "Log Specific Parameter",
      },
      {
        name: "RAE",
        dword: 10,
        bitStart: 15,
        bitEnd: 15,
        description: "Retain Asynchronous Event",
        values: { 0: "Clear event", 1: "Retain event" },
      },
      {
        name: "NUMDL",
        dword: 10,
        bitStart: 16,
        bitEnd: 31,
        description: "Number of Dwords Lower",
      },
      {
        name: "NUMDU",
        dword: 11,
        bitStart: 0,
        bitEnd: 15,
        description: "Number of Dwords Upper",
      },
      {
        name: "LSID",
        dword: 11,
        bitStart: 16,
        bitEnd: 31,
        description: "Log Specific Identifier",
      },
      {
        name: "LPOL",
        dword: 12,
        bitStart: 0,
        bitEnd: 31,
        description: "Log Page Offset Lower",
      },
      {
        name: "LPOU",
        dword: 13,
        bitStart: 0,
        bitEnd: 31,
        description: "Log Page Offset Upper",
      },
      {
        name: "UUID",
        dword: 14,
        bitStart: 0,
        bitEnd: 6,
        description: "UUID Index",
      },
    ],
    relatedCommands: ["admin-async-event"],
  },
  {
    id: "admin-delete-cq",
    name: "Delete I/O Completion Queue",
    opcode: 0x04,
    type: "admin",
    description:
      "Deletes an I/O Completion Queue. All associated SQs must be deleted first.",
    fields: [
      {
        name: "QID",
        dword: 10,
        bitStart: 0,
        bitEnd: 15,
        description: "Queue Identifier — identifies the queue to delete",
      },
    ],
    relatedCommands: ["admin-create-cq"],
  },
  {
    id: "admin-create-cq",
    name: "Create I/O Completion Queue",
    opcode: 0x05,
    type: "admin",
    description:
      "Creates an I/O Completion Queue with the specified attributes.",
    fields: [
      {
        name: "QID",
        dword: 10,
        bitStart: 0,
        bitEnd: 15,
        description: "Queue Identifier",
      },
      {
        name: "QSIZE",
        dword: 10,
        bitStart: 16,
        bitEnd: 31,
        description: "Queue Size — 0-based value",
      },
      {
        name: "PC",
        dword: 11,
        bitStart: 0,
        bitEnd: 0,
        description: "Physically Contiguous",
        values: { 0: "Not contiguous", 1: "Physically contiguous" },
      },
      {
        name: "IEN",
        dword: 11,
        bitStart: 1,
        bitEnd: 1,
        description: "Interrupts Enabled",
        values: { 0: "Disabled", 1: "Enabled" },
      },
      {
        name: "IV",
        dword: 11,
        bitStart: 16,
        bitEnd: 31,
        description: "Interrupt Vector",
      },
    ],
    relatedCommands: ["admin-delete-cq", "admin-create-sq"],
  },
  {
    id: "admin-identify",
    name: "Identify",
    opcode: 0x06,
    type: "admin",
    description:
      "Returns a data structure describing the controller or namespace. The most fundamental admin command.",
    fields: [
      {
        name: "CNS",
        dword: 10,
        bitStart: 0,
        bitEnd: 7,
        description: "Controller or Namespace Structure",
        values: {
          0: "Namespace",
          1: "Controller",
          2: "Active NS List",
          3: "NS Identification Descriptor",
        },
      },
      {
        name: "CNTID",
        dword: 10,
        bitStart: 16,
        bitEnd: 31,
        description: "Controller Identifier",
      },
      {
        name: "NVMSETID",
        dword: 11,
        bitStart: 0,
        bitEnd: 15,
        description: "NVM Set Identifier",
      },
      {
        name: "UUID",
        dword: 14,
        bitStart: 0,
        bitEnd: 6,
        description: "UUID Index",
      },
    ],
    relatedCommands: ["admin-ns-mgmt"],
  },
  {
    id: "admin-abort",
    name: "Abort",
    opcode: 0x08,
    type: "admin",
    description:
      "Aborts a specific command previously submitted to the admin or I/O SQ.",
    fields: [
      {
        name: "SQID",
        dword: 10,
        bitStart: 0,
        bitEnd: 15,
        description: "Submission Queue Identifier",
      },
      {
        name: "CID",
        dword: 10,
        bitStart: 16,
        bitEnd: 31,
        description: "Command Identifier to abort",
      },
    ],
  },
  {
    id: "admin-set-features",
    name: "Set Features",
    opcode: 0x09,
    type: "admin",
    description:
      "Sets the attributes of the specified feature. Used to configure controller behavior.",
    fields: [
      {
        name: "FID",
        dword: 10,
        bitStart: 0,
        bitEnd: 7,
        description: "Feature Identifier",
      },
      {
        name: "SV",
        dword: 10,
        bitStart: 31,
        bitEnd: 31,
        description: "Save — save value across power cycles",
        values: { 0: "Do not save", 1: "Save" },
      },
      {
        name: "CDW11",
        dword: 11,
        bitStart: 0,
        bitEnd: 31,
        description: "Feature-specific value (varies by FID)",
      },
      {
        name: "UUID",
        dword: 14,
        bitStart: 0,
        bitEnd: 6,
        description: "UUID Index",
      },
    ],
    relatedCommands: ["admin-get-features"],
  },
  {
    id: "admin-get-features",
    name: "Get Features",
    opcode: 0x0a,
    type: "admin",
    description:
      "Retrieves the attributes of the specified feature.",
    fields: [
      {
        name: "FID",
        dword: 10,
        bitStart: 0,
        bitEnd: 7,
        description: "Feature Identifier",
      },
      {
        name: "SEL",
        dword: 10,
        bitStart: 8,
        bitEnd: 10,
        description: "Select — which value to return",
        values: {
          0: "Current",
          1: "Default",
          2: "Saved",
          3: "Supported Capabilities",
        },
      },
      {
        name: "UUID",
        dword: 14,
        bitStart: 0,
        bitEnd: 6,
        description: "UUID Index",
      },
    ],
    relatedCommands: ["admin-set-features"],
  },
  {
    id: "admin-async-event",
    name: "Async Event Request",
    opcode: 0x0c,
    type: "admin",
    description:
      "Requests notification of events that require host action. The controller completes this command when an event occurs.",
    fields: [],
    relatedCommands: ["admin-get-log-page"],
  },
  {
    id: "admin-ns-mgmt",
    name: "Namespace Management",
    opcode: 0x0d,
    type: "admin",
    description:
      "Creates, deletes, or manages namespaces on the controller.",
    fields: [
      {
        name: "SEL",
        dword: 10,
        bitStart: 0,
        bitEnd: 3,
        description: "Select — management operation",
        values: { 0: "Create", 1: "Delete" },
      },
    ],
    relatedCommands: ["admin-ns-attach", "admin-identify"],
  },
  {
    id: "admin-fw-commit",
    name: "Firmware Commit",
    opcode: 0x10,
    type: "admin",
    description:
      "Commits a firmware image to a firmware slot. Optionally activates the image.",
    fields: [
      {
        name: "FS",
        dword: 10,
        bitStart: 0,
        bitEnd: 2,
        description: "Firmware Slot — slot to commit to",
      },
      {
        name: "CA",
        dword: 10,
        bitStart: 3,
        bitEnd: 5,
        description: "Commit Action",
        values: {
          0: "Replace image, no activation",
          1: "Replace image and activate on next reset",
          2: "Activate slot on next reset",
          3: "Replace and activate immediately",
        },
      },
      {
        name: "BPID",
        dword: 10,
        bitStart: 31,
        bitEnd: 31,
        description: "Boot Partition ID",
      },
    ],
    relatedCommands: ["admin-fw-download"],
  },
  {
    id: "admin-fw-download",
    name: "Firmware Image Download",
    opcode: 0x11,
    type: "admin",
    description:
      "Downloads a firmware image (or portion) to the controller. Multiple commands may be needed for large images.",
    fields: [
      {
        name: "NUMD",
        dword: 10,
        bitStart: 0,
        bitEnd: 31,
        description: "Number of Dwords — 0-based",
      },
      {
        name: "OFST",
        dword: 11,
        bitStart: 0,
        bitEnd: 31,
        description: "Offset — in dwords",
      },
    ],
    relatedCommands: ["admin-fw-commit"],
  },
  {
    id: "admin-self-test",
    name: "Device Self-test",
    opcode: 0x14,
    type: "admin",
    description:
      "Starts a device self-test operation or aborts an in-progress self-test.",
    fields: [
      {
        name: "STC",
        dword: 10,
        bitStart: 0,
        bitEnd: 3,
        description: "Self-test Code",
        values: {
          1: "Short self-test",
          2: "Extended self-test",
          0xf: "Abort self-test",
        },
      },
    ],
    relatedCommands: ["admin-get-log-page"],
  },
  {
    id: "admin-ns-attach",
    name: "Namespace Attachment",
    opcode: 0x15,
    type: "admin",
    description:
      "Attaches or detaches a namespace to/from a controller.",
    fields: [
      {
        name: "SEL",
        dword: 10,
        bitStart: 0,
        bitEnd: 3,
        description: "Select — attachment operation",
        values: { 0: "Attach", 1: "Detach" },
      },
    ],
    relatedCommands: ["admin-ns-mgmt"],
  },
  {
    id: "admin-keep-alive",
    name: "Keep Alive",
    opcode: 0x18,
    type: "admin",
    description:
      "Sent by host to indicate it is alive. Resets the keep alive timer on the controller.",
    fields: [],
  },
  {
    id: "admin-directive-send",
    name: "Directive Send",
    opcode: 0x19,
    type: "admin",
    description:
      "Sends directive data to the controller.",
    fields: [
      {
        name: "NUMD",
        dword: 10,
        bitStart: 0,
        bitEnd: 31,
        description: "Number of Dwords",
      },
      {
        name: "DOPER",
        dword: 11,
        bitStart: 0,
        bitEnd: 7,
        description: "Directive Operation",
      },
      {
        name: "DTYPE",
        dword: 11,
        bitStart: 8,
        bitEnd: 15,
        description: "Directive Type",
        values: { 0: "Identify", 1: "Streams" },
      },
      {
        name: "DSPEC",
        dword: 11,
        bitStart: 16,
        bitEnd: 31,
        description: "Directive Specific",
      },
    ],
    relatedCommands: ["admin-directive-recv"],
  },
  {
    id: "admin-directive-recv",
    name: "Directive Receive",
    opcode: 0x1a,
    type: "admin",
    description:
      "Receives directive data from the controller.",
    fields: [
      {
        name: "NUMD",
        dword: 10,
        bitStart: 0,
        bitEnd: 31,
        description: "Number of Dwords",
      },
      {
        name: "DOPER",
        dword: 11,
        bitStart: 0,
        bitEnd: 7,
        description: "Directive Operation",
      },
      {
        name: "DTYPE",
        dword: 11,
        bitStart: 8,
        bitEnd: 15,
        description: "Directive Type",
        values: { 0: "Identify", 1: "Streams" },
      },
      {
        name: "DSPEC",
        dword: 11,
        bitStart: 16,
        bitEnd: 31,
        description: "Directive Specific",
      },
    ],
    relatedCommands: ["admin-directive-send"],
  },
  {
    id: "admin-virt-mgmt",
    name: "Virtualization Management",
    opcode: 0x1c,
    type: "admin",
    description:
      "Manages flexible resources between primary and secondary controllers (SR-IOV).",
    fields: [
      {
        name: "ACT",
        dword: 10,
        bitStart: 0,
        bitEnd: 3,
        description: "Action",
        values: {
          1: "Primary Flexible",
          7: "Secondary Offline",
          8: "Secondary Online",
        },
      },
      {
        name: "RT",
        dword: 10,
        bitStart: 8,
        bitEnd: 10,
        description: "Resource Type",
        values: { 0: "VQ Resources", 1: "VI Resources" },
      },
      {
        name: "CNTLID",
        dword: 10,
        bitStart: 16,
        bitEnd: 31,
        description: "Controller Identifier",
      },
      {
        name: "NR",
        dword: 11,
        bitStart: 0,
        bitEnd: 15,
        description: "Number of Resources",
      },
    ],
  },
  {
    id: "admin-doorbell-buf",
    name: "Doorbell Buffer Config",
    opcode: 0x7c,
    type: "admin",
    description:
      "Configures shadow doorbell and EventIdx buffers to reduce MMIO doorbell writes.",
    fields: [
      {
        name: "PRPL",
        dword: 10,
        bitStart: 0,
        bitEnd: 31,
        description: "Shadow Doorbell Buffer PRP Entry Lower",
      },
    ],
  },
  {
    id: "admin-format-nvm",
    name: "Format NVM",
    opcode: 0x80,
    type: "admin",
    description:
      "Formats the NVM media. Low-level format that changes LBA format and optionally performs secure erase.",
    fields: [
      {
        name: "LBAF",
        dword: 10,
        bitStart: 0,
        bitEnd: 3,
        description: "LBA Format — index into the LBA Format table",
      },
      {
        name: "MSET",
        dword: 10,
        bitStart: 4,
        bitEnd: 4,
        description: "Metadata Settings",
        values: { 0: "Separate buffer", 1: "Extended LBA" },
      },
      {
        name: "PI",
        dword: 10,
        bitStart: 5,
        bitEnd: 7,
        description: "Protection Information",
        values: { 0: "Not enabled", 1: "Type 1", 2: "Type 2", 3: "Type 3" },
      },
      {
        name: "PIL",
        dword: 10,
        bitStart: 8,
        bitEnd: 8,
        description: "PI Location",
        values: { 0: "Last 8 bytes", 1: "First 8 bytes" },
      },
      {
        name: "SES",
        dword: 10,
        bitStart: 9,
        bitEnd: 11,
        description: "Secure Erase Settings",
        values: {
          0: "No secure erase",
          1: "User Data Erase",
          2: "Cryptographic Erase",
        },
      },
    ],
    relatedCommands: ["admin-sanitize"],
  },
  {
    id: "admin-security-send",
    name: "Security Send",
    opcode: 0x81,
    type: "admin",
    description:
      "Sends security protocol data to the controller (e.g., TCG Opal commands).",
    fields: [
      {
        name: "NSSF",
        dword: 10,
        bitStart: 0,
        bitEnd: 7,
        description: "NVMe Security Specific Field",
      },
      {
        name: "SPSP0",
        dword: 10,
        bitStart: 8,
        bitEnd: 15,
        description: "SP Specific 0",
      },
      {
        name: "SPSP1",
        dword: 10,
        bitStart: 16,
        bitEnd: 23,
        description: "SP Specific 1",
      },
      {
        name: "SECP",
        dword: 10,
        bitStart: 24,
        bitEnd: 31,
        description: "Security Protocol",
      },
      {
        name: "TL",
        dword: 11,
        bitStart: 0,
        bitEnd: 31,
        description: "Transfer Length (in bytes)",
      },
    ],
    relatedCommands: ["admin-security-recv"],
  },
  {
    id: "admin-security-recv",
    name: "Security Receive",
    opcode: 0x82,
    type: "admin",
    description:
      "Receives security protocol data from the controller.",
    fields: [
      {
        name: "NSSF",
        dword: 10,
        bitStart: 0,
        bitEnd: 7,
        description: "NVMe Security Specific Field",
      },
      {
        name: "SPSP0",
        dword: 10,
        bitStart: 8,
        bitEnd: 15,
        description: "SP Specific 0",
      },
      {
        name: "SPSP1",
        dword: 10,
        bitStart: 16,
        bitEnd: 23,
        description: "SP Specific 1",
      },
      {
        name: "SECP",
        dword: 10,
        bitStart: 24,
        bitEnd: 31,
        description: "Security Protocol",
      },
      {
        name: "AL",
        dword: 11,
        bitStart: 0,
        bitEnd: 31,
        description: "Allocation Length (in bytes)",
      },
    ],
    relatedCommands: ["admin-security-send"],
  },
  {
    id: "admin-sanitize",
    name: "Sanitize",
    opcode: 0x84,
    type: "admin",
    description:
      "Starts a sanitize operation that permanently removes all user data. Affects entire NVM subsystem.",
    fields: [
      {
        name: "SANACT",
        dword: 10,
        bitStart: 0,
        bitEnd: 2,
        description: "Sanitize Action",
        values: {
          1: "Exit Failure Mode",
          2: "Block Erase",
          3: "Overwrite",
          4: "Crypto Erase",
        },
      },
      {
        name: "AUSE",
        dword: 10,
        bitStart: 3,
        bitEnd: 3,
        description: "Allow Unrestricted Sanitize Exit",
        values: { 0: "Restricted", 1: "Unrestricted" },
      },
      {
        name: "OWPASS",
        dword: 10,
        bitStart: 4,
        bitEnd: 7,
        description: "Overwrite Pass Count (0-based)",
      },
      {
        name: "OIPBP",
        dword: 10,
        bitStart: 8,
        bitEnd: 8,
        description: "Overwrite Invert Pattern Between Passes",
        values: { 0: "No invert", 1: "Invert" },
      },
      {
        name: "NDAS",
        dword: 10,
        bitStart: 9,
        bitEnd: 9,
        description: "No Deallocate After Sanitize",
        values: { 0: "Deallocate", 1: "No deallocate" },
      },
      {
        name: "OVRPAT",
        dword: 14,
        bitStart: 0,
        bitEnd: 31,
        description: "Overwrite Pattern (32-bit pattern written to NVM)",
      },
    ],
    relatedCommands: ["admin-format-nvm"],
  },
  {
    id: "admin-get-lba-status",
    name: "Get LBA Status",
    opcode: 0x86,
    type: "admin",
    description:
      "Returns information about potentially unrecoverable LBAs.",
    fields: [
      {
        name: "SLBA_L",
        dword: 10,
        bitStart: 0,
        bitEnd: 31,
        description: "Starting LBA (Lower 32 bits)",
      },
      {
        name: "SLBA_U",
        dword: 11,
        bitStart: 0,
        bitEnd: 31,
        description: "Starting LBA (Upper 32 bits)",
      },
      {
        name: "MNDW",
        dword: 12,
        bitStart: 0,
        bitEnd: 31,
        description: "Maximum Number of Dwords",
      },
      {
        name: "ATYPE",
        dword: 13,
        bitStart: 0,
        bitEnd: 7,
        description: "Action Type",
      },
      {
        name: "RL",
        dword: 13,
        bitStart: 16,
        bitEnd: 31,
        description: "Range Length",
      },
    ],
  },
];
