import { NvmeCommand } from "./types";

export const ioCommands: NvmeCommand[] = [
  {
    id: "io-flush",
    name: "Flush",
    opcode: 0x00,
    type: "io",
    description:
      "Commits all data and metadata in volatile write cache to non-volatile media. Ensures durability.",
    fields: [],
    relatedCommands: ["io-write"],
  },
  {
    id: "io-write",
    name: "Write",
    opcode: 0x01,
    type: "io",
    description:
      "Writes data and optionally metadata to the NVM. The most common I/O command.",
    fields: [
      {
        name: "SLBA_L",
        dword: 10,
        bitStart: 0,
        bitEnd: 31,
        description: "Starting LBA (Lower 32 bits)",
      },
      {
        name: "SLBA_U",
        dword: 11,
        bitStart: 0,
        bitEnd: 31,
        description: "Starting LBA (Upper 32 bits)",
      },
      {
        name: "NLB",
        dword: 12,
        bitStart: 0,
        bitEnd: 15,
        description: "Number of Logical Blocks (0-based)",
      },
      {
        name: "DTYPE",
        dword: 12,
        bitStart: 20,
        bitEnd: 23,
        description: "Directive Type",
        values: { 0: "None", 1: "Streams" },
      },
      {
        name: "STC",
        dword: 12,
        bitStart: 24,
        bitEnd: 24,
        description: "Storage Tag Check",
        values: { 0: "Do not check", 1: "Check" },
      },
      {
        name: "PRINFO",
        dword: 12,
        bitStart: 26,
        bitEnd: 29,
        description: "Protection Information field",
      },
      {
        name: "FUA",
        dword: 12,
        bitStart: 30,
        bitEnd: 30,
        description: "Force Unit Access — bypass volatile cache",
        values: { 0: "Normal", 1: "Force to NVM" },
      },
      {
        name: "LR",
        dword: 12,
        bitStart: 31,
        bitEnd: 31,
        description: "Limited Retry",
        values: { 0: "Normal retry", 1: "Limited retry" },
      },
      {
        name: "DSM",
        dword: 13,
        bitStart: 0,
        bitEnd: 7,
        description:
          "Dataset Management — access frequency, latency, sequential hints",
      },
      {
        name: "DSPEC",
        dword: 13,
        bitStart: 16,
        bitEnd: 31,
        description: "Directive Specific (Stream Identifier)",
      },
      {
        name: "ILBRT",
        dword: 14,
        bitStart: 0,
        bitEnd: 31,
        description: "Initial Logical Block Reference Tag",
      },
      {
        name: "LBAT",
        dword: 15,
        bitStart: 0,
        bitEnd: 15,
        description: "Logical Block Application Tag",
      },
      {
        name: "LBATM",
        dword: 15,
        bitStart: 16,
        bitEnd: 31,
        description: "Logical Block Application Tag Mask",
      },
    ],
    relatedCommands: ["io-read", "io-flush", "io-write-zeroes"],
  },
  {
    id: "io-read",
    name: "Read",
    opcode: 0x02,
    type: "io",
    description:
      "Reads data and optionally metadata from the NVM. The most common read operation.",
    fields: [
      {
        name: "SLBA_L",
        dword: 10,
        bitStart: 0,
        bitEnd: 31,
        description: "Starting LBA (Lower 32 bits)",
      },
      {
        name: "SLBA_U",
        dword: 11,
        bitStart: 0,
        bitEnd: 31,
        description: "Starting LBA (Upper 32 bits)",
      },
      {
        name: "NLB",
        dword: 12,
        bitStart: 0,
        bitEnd: 15,
        description: "Number of Logical Blocks (0-based)",
      },
      {
        name: "PRINFO",
        dword: 12,
        bitStart: 26,
        bitEnd: 29,
        description: "Protection Information field",
      },
      {
        name: "FUA",
        dword: 12,
        bitStart: 30,
        bitEnd: 30,
        description: "Force Unit Access",
        values: { 0: "Normal", 1: "Force from NVM" },
      },
      {
        name: "LR",
        dword: 12,
        bitStart: 31,
        bitEnd: 31,
        description: "Limited Retry",
        values: { 0: "Normal retry", 1: "Limited retry" },
      },
      {
        name: "DSM",
        dword: 13,
        bitStart: 0,
        bitEnd: 7,
        description: "Dataset Management — access frequency, latency hints",
      },
      {
        name: "ILBRT",
        dword: 14,
        bitStart: 0,
        bitEnd: 31,
        description: "Initial Logical Block Reference Tag (Expected)",
      },
      {
        name: "ELBAT",
        dword: 15,
        bitStart: 0,
        bitEnd: 15,
        description: "Expected Logical Block Application Tag",
      },
      {
        name: "ELBATM",
        dword: 15,
        bitStart: 16,
        bitEnd: 31,
        description: "Expected Logical Block Application Tag Mask",
      },
    ],
    relatedCommands: ["io-write", "io-compare"],
  },
  {
    id: "io-write-uncorrectable",
    name: "Write Uncorrectable",
    opcode: 0x04,
    type: "io",
    description:
      "Marks a range of logical blocks as invalid. Subsequent reads return an error.",
    fields: [
      {
        name: "SLBA_L",
        dword: 10,
        bitStart: 0,
        bitEnd: 31,
        description: "Starting LBA (Lower 32 bits)",
      },
      {
        name: "SLBA_U",
        dword: 11,
        bitStart: 0,
        bitEnd: 31,
        description: "Starting LBA (Upper 32 bits)",
      },
      {
        name: "NLB",
        dword: 12,
        bitStart: 0,
        bitEnd: 15,
        description: "Number of Logical Blocks (0-based)",
      },
    ],
  },
  {
    id: "io-compare",
    name: "Compare",
    opcode: 0x05,
    type: "io",
    description:
      "Reads and compares data from NVM to the data transferred in the command. Used for atomic check-and-set operations.",
    fields: [
      {
        name: "SLBA_L",
        dword: 10,
        bitStart: 0,
        bitEnd: 31,
        description: "Starting LBA (Lower 32 bits)",
      },
      {
        name: "SLBA_U",
        dword: 11,
        bitStart: 0,
        bitEnd: 31,
        description: "Starting LBA (Upper 32 bits)",
      },
      {
        name: "NLB",
        dword: 12,
        bitStart: 0,
        bitEnd: 15,
        description: "Number of Logical Blocks (0-based)",
      },
      {
        name: "PRINFO",
        dword: 12,
        bitStart: 26,
        bitEnd: 29,
        description: "Protection Information field",
      },
      {
        name: "FUA",
        dword: 12,
        bitStart: 30,
        bitEnd: 30,
        description: "Force Unit Access",
        values: { 0: "Normal", 1: "Force from NVM" },
      },
      {
        name: "ILBRT",
        dword: 14,
        bitStart: 0,
        bitEnd: 31,
        description: "Expected Initial Logical Block Reference Tag",
      },
      {
        name: "ELBAT",
        dword: 15,
        bitStart: 0,
        bitEnd: 15,
        description: "Expected Logical Block Application Tag",
      },
      {
        name: "ELBATM",
        dword: 15,
        bitStart: 16,
        bitEnd: 31,
        description: "Expected Logical Block Application Tag Mask",
      },
    ],
    relatedCommands: ["io-read", "io-write"],
  },
  {
    id: "io-write-zeroes",
    name: "Write Zeroes",
    opcode: 0x08,
    type: "io",
    description:
      "Writes zeroes to a range of logical blocks. More efficient than a regular write of zeroed data.",
    fields: [
      {
        name: "SLBA_L",
        dword: 10,
        bitStart: 0,
        bitEnd: 31,
        description: "Starting LBA (Lower 32 bits)",
      },
      {
        name: "SLBA_U",
        dword: 11,
        bitStart: 0,
        bitEnd: 31,
        description: "Starting LBA (Upper 32 bits)",
      },
      {
        name: "NLB",
        dword: 12,
        bitStart: 0,
        bitEnd: 15,
        description: "Number of Logical Blocks (0-based)",
      },
      {
        name: "DEAC",
        dword: 12,
        bitStart: 25,
        bitEnd: 25,
        description: "Deallocate",
        values: { 0: "No deallocate", 1: "Deallocate" },
      },
      {
        name: "PRINFO",
        dword: 12,
        bitStart: 26,
        bitEnd: 29,
        description: "Protection Information field",
      },
      {
        name: "FUA",
        dword: 12,
        bitStart: 30,
        bitEnd: 30,
        description: "Force Unit Access",
        values: { 0: "Normal", 1: "Force to NVM" },
      },
      {
        name: "LR",
        dword: 12,
        bitStart: 31,
        bitEnd: 31,
        description: "Limited Retry",
        values: { 0: "Normal retry", 1: "Limited retry" },
      },
      {
        name: "ILBRT",
        dword: 14,
        bitStart: 0,
        bitEnd: 31,
        description: "Initial Logical Block Reference Tag",
      },
      {
        name: "LBAT",
        dword: 15,
        bitStart: 0,
        bitEnd: 15,
        description: "Logical Block Application Tag",
      },
      {
        name: "LBATM",
        dword: 15,
        bitStart: 16,
        bitEnd: 31,
        description: "Logical Block Application Tag Mask",
      },
    ],
    relatedCommands: ["io-write", "io-dataset-mgmt"],
  },
  {
    id: "io-dataset-mgmt",
    name: "Dataset Management (TRIM)",
    opcode: 0x09,
    type: "io",
    description:
      "Indicates attributes of ranges of logical blocks. Most commonly used for TRIM/deallocate to inform the controller that blocks are no longer in use.",
    fields: [
      {
        name: "NR",
        dword: 10,
        bitStart: 0,
        bitEnd: 7,
        description: "Number of Ranges (0-based, max 256)",
      },
      {
        name: "IDR",
        dword: 11,
        bitStart: 0,
        bitEnd: 0,
        description: "Integral Dataset for Read",
        values: { 0: "No hint", 1: "Integral" },
      },
      {
        name: "IDW",
        dword: 11,
        bitStart: 1,
        bitEnd: 1,
        description: "Integral Dataset for Write",
        values: { 0: "No hint", 1: "Integral" },
      },
      {
        name: "AD",
        dword: 11,
        bitStart: 2,
        bitEnd: 2,
        description: "Deallocate (TRIM)",
        values: { 0: "No deallocate", 1: "Deallocate" },
      },
    ],
    relatedCommands: ["io-write-zeroes"],
  },
  {
    id: "io-verify",
    name: "Verify",
    opcode: 0x0c,
    type: "io",
    description:
      "Verifies data in a range of logical blocks without transferring data to the host.",
    fields: [
      {
        name: "SLBA_L",
        dword: 10,
        bitStart: 0,
        bitEnd: 31,
        description: "Starting LBA (Lower 32 bits)",
      },
      {
        name: "SLBA_U",
        dword: 11,
        bitStart: 0,
        bitEnd: 31,
        description: "Starting LBA (Upper 32 bits)",
      },
      {
        name: "NLB",
        dword: 12,
        bitStart: 0,
        bitEnd: 15,
        description: "Number of Logical Blocks (0-based)",
      },
      {
        name: "PRINFO",
        dword: 12,
        bitStart: 26,
        bitEnd: 29,
        description: "Protection Information field",
      },
      {
        name: "FUA",
        dword: 12,
        bitStart: 30,
        bitEnd: 30,
        description: "Force Unit Access",
        values: { 0: "Normal", 1: "Force from NVM" },
      },
      {
        name: "LR",
        dword: 12,
        bitStart: 31,
        bitEnd: 31,
        description: "Limited Retry",
        values: { 0: "Normal retry", 1: "Limited retry" },
      },
      {
        name: "ILBRT",
        dword: 14,
        bitStart: 0,
        bitEnd: 31,
        description: "Expected Initial Logical Block Reference Tag",
      },
      {
        name: "ELBAT",
        dword: 15,
        bitStart: 0,
        bitEnd: 15,
        description: "Expected Logical Block Application Tag",
      },
      {
        name: "ELBATM",
        dword: 15,
        bitStart: 16,
        bitEnd: 31,
        description: "Expected Logical Block Application Tag Mask",
      },
    ],
    relatedCommands: ["io-read", "io-compare"],
  },
  {
    id: "io-reservation-register",
    name: "Reservation Register",
    opcode: 0x0d,
    type: "io",
    description:
      "Registers, unregisters, or replaces a reservation key.",
    fields: [
      {
        name: "RREGA",
        dword: 10,
        bitStart: 0,
        bitEnd: 2,
        description: "Reservation Register Action",
        values: { 0: "Register", 1: "Unregister", 2: "Replace" },
      },
      {
        name: "IEKEY",
        dword: 10,
        bitStart: 3,
        bitEnd: 3,
        description: "Ignore Existing Key",
        values: { 0: "Check key", 1: "Ignore key" },
      },
      {
        name: "CPTPL",
        dword: 10,
        bitStart: 30,
        bitEnd: 31,
        description: "Change Persist Through Power Loss",
        values: { 0: "No change", 2: "Clear", 3: "Set" },
      },
    ],
    relatedCommands: [
      "io-reservation-report",
      "io-reservation-acquire",
      "io-reservation-release",
    ],
  },
  {
    id: "io-reservation-report",
    name: "Reservation Report",
    opcode: 0x0e,
    type: "io",
    description:
      "Returns a data structure describing the reservation status.",
    fields: [
      {
        name: "NUMD",
        dword: 10,
        bitStart: 0,
        bitEnd: 31,
        description: "Number of Dwords (0-based)",
      },
      {
        name: "EDS",
        dword: 11,
        bitStart: 0,
        bitEnd: 0,
        description: "Extended Data Structure",
        values: { 0: "Standard", 1: "Extended" },
      },
    ],
    relatedCommands: ["io-reservation-register"],
  },
  {
    id: "io-reservation-acquire",
    name: "Reservation Acquire",
    opcode: 0x11,
    type: "io",
    description:
      "Acquires, preempts, or preempt-and-aborts a reservation.",
    fields: [
      {
        name: "RACQA",
        dword: 10,
        bitStart: 0,
        bitEnd: 2,
        description: "Reservation Acquire Action",
        values: { 0: "Acquire", 1: "Preempt", 2: "Preempt and Abort" },
      },
      {
        name: "IEKEY",
        dword: 10,
        bitStart: 3,
        bitEnd: 3,
        description: "Ignore Existing Key",
        values: { 0: "Check key", 1: "Ignore key" },
      },
      {
        name: "RTYPE",
        dword: 10,
        bitStart: 8,
        bitEnd: 15,
        description: "Reservation Type",
        values: {
          1: "Write Exclusive",
          2: "Exclusive Access",
          3: "Write Exclusive - Registrants Only",
          4: "Exclusive Access - Registrants Only",
          5: "Write Exclusive - All Registrants",
          6: "Exclusive Access - All Registrants",
        },
      },
    ],
    relatedCommands: ["io-reservation-register", "io-reservation-release"],
  },
  {
    id: "io-reservation-release",
    name: "Reservation Release",
    opcode: 0x15,
    type: "io",
    description:
      "Releases or clears a reservation.",
    fields: [
      {
        name: "RRELA",
        dword: 10,
        bitStart: 0,
        bitEnd: 2,
        description: "Reservation Release Action",
        values: { 0: "Release", 1: "Clear" },
      },
      {
        name: "IEKEY",
        dword: 10,
        bitStart: 3,
        bitEnd: 3,
        description: "Ignore Existing Key",
        values: { 0: "Check key", 1: "Ignore key" },
      },
      {
        name: "RTYPE",
        dword: 10,
        bitStart: 8,
        bitEnd: 15,
        description: "Reservation Type",
        values: {
          1: "Write Exclusive",
          2: "Exclusive Access",
          3: "Write Exclusive - Registrants Only",
          4: "Exclusive Access - Registrants Only",
          5: "Write Exclusive - All Registrants",
          6: "Exclusive Access - All Registrants",
        },
      },
    ],
    relatedCommands: ["io-reservation-register", "io-reservation-acquire"],
  },
];
